config/routes.rb
Rails.application.routes.draw do
  resources :user_notenplans
  resources :marks
  resources :subjects
  resources :notenplans
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    authenticated :user do
      root :to => 'notenplans#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users
end

app/models/user_notenplan.rb
class UserNotenplan < ActiveRecord::Base
  belongs_to :notenplan
  belongs_to :user
end

app/controllers/user_notenplans_controller.rb
class UserNotenplansController < ApplicationController
  before_action :set_user_notenplan, only: [:show, :edit, :update, :destroy]

  # GET /user_notenplans/1
  # GET /user_notenplans/1.json
  def show
  end

  # GET /user_notenplans/new
  def new
    @notenplan_id = params[:notenplan_id]
    @user_notenplan = UserNotenplan.new
  end

  # GET /user_notenplans/1/edit
  def edit
  end

  # POST /user_notenplans
  # POST /user_notenplans.json
  def create
    user = User.find_by(email: user_notenplan_params[:user_id])
    if (!user.nil?)
      @user_notenplan = UserNotenplan.find_by(notenplan_id: user_notenplan_params[:notenplan_id], user_id: user.id)
      if @user_notenplan.nil?
        @user_notenplan = UserNotenplan.create(notenplan_id: user_notenplan_params[:notenplan_id], user_id: user.id, admin: user_notenplan_params[:admin])
      else
        @user_notenplan.update(admin: user_notenplan_params[:admin])
      end
      notenplan = Notenplan.find_by(id: user_notenplan_params[:notenplan_id])
      respond_to do |format|
        if @user_notenplan.save
          format.html { redirect_to notenplan, notice: 'User notenplan was successfully created.' }
          format.json { render :show, status: :created, location: @user_notenplan }
        else
          format.html { render :new, notenplan_id: user_notenplan_params[:notenplan_id] }
          format.json { render json: @user_notenplan.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to new_user_notenplan_path, notenplan_id: user_notenplan_params[:notenplan_id], notice: 'User wurde nicht gefunden'
    end
  end

  # PATCH/PUT /user_notenplans/1
  # PATCH/PUT /user_notenplans/1.json
  def update
    respond_to do |format|
      if @user_notenplan.update(user_notenplan_params)
        format.html { redirect_to @user_notenplan, notice: 'User notenplan was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_notenplan }
      else
        format.html { render :edit }
        format.json { render json: @user_notenplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_notenplans/1
  # DELETE /user_notenplans/1.json
  def destroy
    @user_notenplan.destroy
    respond_to do |format|
      format.html { redirect_to user_notenplans_url, notice: 'User notenplan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_notenplan
      @user_notenplan = UserNotenplan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_notenplan_params
      params.require(:user_notenplan).permit(:user_id, :notenplan_id, :admin)
    end
end

app/helpers/user_notenplans_helper.rb
module UserNotenplansHelper
end

app/views/user_notenplans/_form.html.erb
<%= form_for(@user_notenplan) do |f| %>
  <% if @user_notenplan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_notenplan.errors.count, "error") %> prohibited this user_notenplan from being saved:</h2>

      <ul>
      <% @user_notenplan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'EMail' %><br>
    <%= f.text_field :user_id, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :notenplan_id, class: 'form-control', value: @notenplan_id %>
  </div>
  <div class="form-group">
    <%= f.label 'Admin' %><br>
    <%= f.check_box :admin, class: 'form-control checkbox' %>
  </div>
  <div class="actions">
    <%= f.submit 'Freigabe erstellen', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/user_notenplans/edit.html.erb
<h1>Notenplan bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_notenplan %> |
<%= link_to 'Back', user_notenplans_path %>

app/views/user_notenplans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Notenplans</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Notenplan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_notenplans.each do |user_notenplan| %>
      <tr>
        <td><%= user_notenplan.user %></td>
        <td><%= user_notenplan.notenplan %></td>
        <td><%= link_to 'Show', user_notenplan %></td>
        <td><%= link_to 'Edit', edit_user_notenplan_path(user_notenplan) %></td>
        <td><%= link_to 'Destroy', user_notenplan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User notenplan', new_user_notenplan_path %>

app/views/user_notenplans/new.html.erb
<h1>Notenplan freigeben</h1>

<%= render 'form' %>

<%= link_to 'Zurück', notenplans_path, class: 'btn btn-default' %>

app/views/user_notenplans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_notenplan.user %>
</p>

<p>
  <strong>Notenplan:</strong>
  <%= @user_notenplan.notenplan %>
</p>

<%= link_to 'Edit', edit_user_notenplan_path(@user_notenplan) %> |
<%= link_to 'Back', user_notenplans_path %>