config/routes.rb
Rails.application.routes.draw do
  resources :user_notenplans
  resources :marks
  resources :subjects
  resources :notenplans
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    authenticated :user do
      root :to => 'notenplans#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users
end

app/models/subject.rb
class Subject < ActiveRecord::Base

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]


  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
    @subjects = Subject.all
    session[:notenplan_id] = params[:notenplan]
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    subject_params[:name].each do |subject_name|
      if (subject_name != "")
        subject = Subject.find_or_create_by(name: subject_name)
        Mark.find_or_create_by(notenplan_id: session[:notenplan_id], subject: subject)
      end
    end
    notenplan = Notenplan.find_by(id: session[:notenplan_id])
    redirect_to notenplan, notice: 'Das Fach wurde erfolgreich erstellt.'
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Das Fach wurde erfolgreich geändert.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Das Fach wurde erfolgreich gelöscht.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:number,:name => [])
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.select(:name, @subjects.map{ |subject| [subject.name] }, {}, { class: 'bootstrap-select2 form-control selecter', multiple: true }) %>
  </div>
  <div class="actions">
    <%= f.submit 'Fächer hinzufügen', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Fach bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @subject %> |
<%= link_to 'Zurück', subjects_path %>

app/views/subjects/new.html.erb
<h1>Neue Fächer</h1>

<%= render 'form' %>

<%= link_to 'Zurück', notenplans_path, class: 'btn btn-default' %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<%= link_to 'Bearbeiten', edit_subject_path(@subject) %> |
<%= link_to 'Zurück', subjects_path %>