config/routes.rb
Rails.application.routes.draw do
  resources :user_notenplans
  resources :marks
  resources :subjects
  resources :notenplans
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    authenticated :user do
      root :to => 'notenplans#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users
end

app/models/notenplan.rb
class Notenplan < ActiveRecord::Base
  validates :name, presence: true
  has_many :marks, dependent: :delete_all
  has_many :user_notenplans, dependent: :delete_all
  has_many :users, through: :user_notenplans
  belongs_to :owner, class_name: 'User'
end

app/controllers/notenplans_controller.rb
class NotenplansController < ApplicationController
  before_action :authenticate_user!
  before_action :set_notenplan, only: [:show, :edit, :update, :destroy]

  # GET /notenplans
  # GET /notenplans.json
  def index
    @notenplans = current_user.notenplans.all
  end

  # GET /notenplans/1
  # GET /notenplans/1.json
  def show
    if access_allowed
      @subjects = []
      special_marks = @notenplan.marks.where(mark: nil)
      special_marks.each do |special_mark|
          @subjects << {subject: special_mark.subject, marks:  @notenplan.marks.where(subject_id: special_mark.subject.id)}
      end
    else
      redirect_to notenplans_path, notice: 'Sie dürfen nicht auf diesen Notenplan zugreifen'
    end
  end

  # GET /notenplans/new
  def new
    @notenplan = Notenplan.new
  end

  # GET /notenplans/1/edit
  def edit
    if (!admin_access(@notenplan))
      redirect_to notenplans_path, notice: 'Sie dürfen diesen Notenplan nicht bearbeiten'
    end
  end

  # POST /notenplans
  # POST /notenplans.json
  def create
    @notenplan = Notenplan.create(name: notenplan_params['name'], description: notenplan_params['description'], owner: current_user)
    @userNotenplan = UserNotenplan.create(notenplan: @notenplan, user: current_user, admin: true)

    respond_to do |format|
      if @notenplan.valid? && @userNotenplan.valid?
        format.html { redirect_to new_subject_path(notenplan: @notenplan), notice: 'Notenplan wurde erfolgreich erstellt.' }
        format.json { render :show, status: :created, location: @notenplan }
      else
        format.html { render :new }
        format.json { render json: @notenplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notenplans/1
  # PATCH/PUT /notenplans/1.json
  def update
    respond_to do |format|
      if @notenplan.update(notenplan_params)
        format.html { redirect_to @notenplan, notice: 'Notenplan wurde erfolgreich geändert.' }
        format.json { render :show, status: :ok, location: @notenplan }
      else
        format.html { render :edit }
        format.json { render json: @notenplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notenplans/1
  # DELETE /notenplans/1.json
  def destroy
    @notenplan.destroy
    respond_to do |format|
      format.html { redirect_to notenplans_url, notice: 'Notenplan wurde erfolgreich gelöscht.' }
      format.json { head :no_content }
    end
  end

  def access_allowed
    current_user.notenplans.each do |notenplan|
        if notenplan == @notenplan
          return true
        end
    end
    return false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notenplan
      @notenplan = Notenplan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notenplan_params
      params.require(:notenplan).permit(:name, :description)
    end
end

app/helpers/notenplans_helper.rb
module NotenplansHelper
end

app/views/notenplans/_form.html.erb
<%= form_for(@notenplan) do |f| %>
  <% if @notenplan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notenplan.errors.count, "Fehler") %> prohibited this notenplan from being saved:</h2>

      <ul>
      <% @notenplan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Name' %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label 'Beschreibung' %><br>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Notenplan erstellen', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/notenplans/edit.html.erb
<h1>Notenplan bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Zurück', notenplans_path, class: 'btn btn-default' %>

app/views/notenplans/index.html.erb
<h1>Notenpläne</h1>


<% if @notenplans.count == 0 %>
  <br>
  <p>Keine Notenpläne vorhanden.</p>
<% else %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Beschreibung</th>
      <th>Ersteller</th>
      <th colspan="3" class="col-md-3"></th>
    </tr>
  </thead>

  <tbody>
      <% @notenplans.each do |notenplan| %>
        <tr>
          <td><%= notenplan.name %></td>
          <td><%= notenplan.description %></td>
          <td><%= notenplan.owner.email if notenplan.owner.present? %></td>
          <td><%= link_to 'Anzeigen', notenplan, class: 'btn btn-default' %></td>
          <td><%= link_to 'Bearbeiten', edit_notenplan_path(notenplan), class: 'btn btn-primary' if  admin_access(notenplan) %></td>
          <td><%= link_to 'Löschen', notenplan, method: :delete, data: { confirm: 'Sind sie sicher?' }, class: 'btn btn-danger' if admin_access(notenplan) %>
          </td>
        </tr>
      <% end %>
  </tbody>
</table>
<% end %>

<br>

<%= link_to 'Neuer Notenplan', new_notenplan_path, class: 'btn btn-primary' %>

app/views/notenplans/new.html.erb
<h1>Neuer Notenplan</h1>

<%= render 'form' %>

<%= link_to 'Zurück', notenplans_path, class: 'btn btn-default' %>

app/views/notenplans/show.html.erb
<% @admin = admin_access(@notenplan) %>

<h1><%= @notenplan.name %></h1>
<h4><i><%= @notenplan.description %></i></h4><br>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Fach</th>
      <th>Noten</th>
      <th>Kurztests</th>
      <th>Durchschnitt</th>
      <% if @admin %>
      <th>Note hinzufügen</th>
      <% end %>
    </tr>
  </thead>

<% subject_counter = 0 %>
<% total_marks = 0.0 %>
<% @subjects.each do |subject| %>
  <tbody>
    <tr>
      <td><%= subject[:subject].name %></td>
      <% total = 0.0 %>
      <% counter = 0 %>
      <% shorttests = [] %>
      <td>
      <% subject[:marks].each do |mark| %>
        <% if (!mark.mark.nil? && !mark.shorttest) %>
          <p class="btn" data-toggle="tooltip" data-placement="top" title="Gewichtung: <%= mark.weighting %>"><%= mark.mark %></p>
          <% if @admin %>
            <%= link_to mark, method: :delete, data: { confirm: 'Sind sie sicher?' }, class: 'btn btn-danger btn-sm delete_note' do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          <% end %>
          <% total += mark.mark * mark.weighting %>
          <% counter += mark.weighting %>
        <% elsif !mark.mark.nil? %>
          <% shorttests << mark %>
        <% end %>
      <% end %>
      </td>
      <td>
        <% total_shorttests = 0.0 %>
        <% shorttest_counter = 0 %>
        <% shorttests.each do |shorttest| %>
          <p class="btn" data-toggle="tooltip" data-placement="top" title="Gewichtung: <%= shorttest.weighting %>"><%= shorttest.mark %></p>
          <% total_shorttests += shorttest.mark * shorttest.weighting %>
          <% shorttest_counter += shorttest.weighting %>
          <% if @admin %>
            <%= link_to shorttest, method: :delete, data: { confirm: 'Sind sie sicher?' }, class: 'btn btn-danger btn-sm delete_note' do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          <% end %>
        <% end %>
        <% if shorttests.count > 0 %>
          <% counter += 1 %>
          <% total += total_shorttests / shorttest_counter %>
        <% end %>
      </td>
      <td>
      <% if counter > 0 %>
        <b><%= number_with_precision(total / counter, :precision => 2) %></b>
        <% total_marks += total / counter %>
        <% subject_counter += 1 %>
      <% end %>
      </td>
      <% if @admin %>
      <td><%= link_to 'Neue Note', new_mark_path(notenplan_id: @notenplan.id, subject_id: subject[:subject].id), class: 'btn btn-primary btn-sm' %></td>
      <% end %>
    </tr>
  </tbody>
<% end %>
</table>

<p style="text-align: right; font-size: 16px;">Gesamtdurchschnitt: <b><%= number_with_precision(total_marks / subject_counter, :precision => 2) if subject_counter > 0 %></b></p>
<br><br>
<% if @admin %>
  <%= link_to 'Fach hinzufügen', new_subject_path(notenplan: @notenplan), class: 'btn btn-primary' %>
  <%= link_to 'User berechtigen', new_user_notenplan_path(notenplan_id: @notenplan), class: 'btn btn-primary' %>
<% end %>
<br><br>
<%= link_to 'Zurück', notenplans_path, class: 'btn btn-default' %>

<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>