config/routes.rb
Rails.application.routes.draw do
  resources :user_notenplans
  resources :marks
  resources :subjects
  resources :notenplans
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    authenticated :user do
      root :to => 'notenplans#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :users
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'warning' ? 'danger' : 'success' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_app.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
<li><%= link_to 'Neuer Notenplan', new_notenplan_path %></li>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Benutzer', users_path %></li>
  <li><%= link_to 'Konto bearbeiten', edit_user_registration_path %></li>
  <li><%= link_to 'Abmelden', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Anmelden', new_user_session_path %></li>
  <li><%= link_to 'Registrieren', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a><%= link_to 'Mysia', notenplans_url, class: 'navbar-brand' %></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-left">
        <%= render 'layouts/nav_links_for_app' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/nav_links_for_auth' %>
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Info', page_path('info') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mysia" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Mysia" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <script data-turbolinks-track="true" src="/assets/application.js"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container">
        <div class="row">
       <%= render 'layouts/messages' %>
       <%= yield %>
     </div>
       </div>
    </main>
  </body>
</html>